-- Hybrid Report System Tables for SQL Server 2008
-- Compatible with SQL Server 2008 syntax

-- 1. Report Configuration Table (Hybrid approach)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DBREPORTCONFIG]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DBREPORTCONFIG] (
        [ID] INT IDENTITY(1,1) NOT NULL,
        [KODEREPORT] NVARCHAR(50) NOT NULL,
        [CONFIG_TYPE] NVARCHAR(20) NOT NULL CHECK ([CONFIG_TYPE] IN ('FRONTEND', 'BACKEND', 'SHARED')),
        [STOREDPROC] NVARCHAR(200) NULL,
        [CONFIG_JSON] NTEXT NULL,
        [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
        [CREATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_DBREPORTCONFIG] PRIMARY KEY CLUSTERED ([ID] ASC)
    )

    -- Create indexes
    CREATE NONCLUSTERED INDEX [IX_REPORTCONFIG_CODE_TYPE] ON [dbo].[DBREPORTCONFIG]
    ([KODEREPORT] ASC, [CONFIG_TYPE] ASC)

    CREATE NONCLUSTERED INDEX [IX_REPORTCONFIG_ACTIVE] ON [dbo].[DBREPORTCONFIG]
    ([IS_ACTIVE] ASC)

    PRINT '✅ Table DBREPORTCONFIG created successfully'
END
ELSE
BEGIN
    PRINT 'ℹ️ Table DBREPORTCONFIG already exists'
END

-- 2. Report Header Configuration (Separate for performance)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DBREPORTHEADER]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DBREPORTHEADER] (
        [ID] INT IDENTITY(1,1) NOT NULL,
        [KODEREPORT] NVARCHAR(50) NOT NULL,
        [TITLE] NVARCHAR(200) NULL,
        [SUBTITLE] NVARCHAR(200) NULL,
        [SHOW_DATE] BIT NOT NULL DEFAULT 1,
        [SHOW_PARAMS] BIT NOT NULL DEFAULT 1,
        [SHOW_LOGO] BIT NOT NULL DEFAULT 0,
        [ORIENTATION] NVARCHAR(20) NOT NULL DEFAULT 'PORTRAIT' CHECK ([ORIENTATION] IN ('PORTRAIT', 'LANDSCAPE')),
        [PAGE_SIZE] NVARCHAR(20) NOT NULL DEFAULT 'A4',
        [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
        [CREATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_DBREPORTHEADER] PRIMARY KEY CLUSTERED ([ID] ASC)
    )

    -- Create indexes
    CREATE NONCLUSTERED INDEX [IX_REPORTHEADER_CODE] ON [dbo].[DBREPORTHEADER]
    ([KODEREPORT] ASC)

    CREATE NONCLUSTERED INDEX [IX_REPORTHEADER_ACTIVE] ON [dbo].[DBREPORTHEADER]
    ([IS_ACTIVE] ASC)

    PRINT '✅ Table DBREPORTHEADER created successfully'
END
ELSE
BEGIN
    PRINT 'ℹ️ Table DBREPORTHEADER already exists'
END

-- 3. Report Column Configuration (Separate for performance)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DBREPORTCOLUMN]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DBREPORTCOLUMN] (
        [ID] INT IDENTITY(1,1) NOT NULL,
        [KODEREPORT] NVARCHAR(50) NOT NULL,
        [COLUMN_NAME] NVARCHAR(100) NOT NULL,
        [COLUMN_LABEL] NVARCHAR(200) NOT NULL,
        [WIDTH] INT NOT NULL DEFAULT 100,
        [ALIGNMENT] NVARCHAR(20) NOT NULL DEFAULT 'LEFT' CHECK ([ALIGNMENT] IN ('LEFT', 'CENTER', 'RIGHT')),
        [DATA_TYPE] NVARCHAR(50) NOT NULL DEFAULT 'TEXT',
        [FORMAT_MASK] NVARCHAR(100) NULL,
        [SORT_ORDER] INT NOT NULL DEFAULT 0,
        [IS_VISIBLE] BIT NOT NULL DEFAULT 1,
        [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
        [CREATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_DBREPORTCOLUMN] PRIMARY KEY CLUSTERED ([ID] ASC)
    )

    -- Create indexes
    CREATE NONCLUSTERED INDEX [IX_REPORTCOLUMN_CODE_ORDER] ON [dbo].[DBREPORTCOLUMN]
    ([KODEREPORT] ASC, [SORT_ORDER] ASC)

    CREATE NONCLUSTERED INDEX [IX_REPORTCOLUMN_CODE_VISIBLE] ON [dbo].[DBREPORTCOLUMN]
    ([KODEREPORT] ASC, [IS_VISIBLE] ASC)

    CREATE NONCLUSTERED INDEX [IX_REPORTCOLUMN_ACTIVE] ON [dbo].[DBREPORTCOLUMN]
    ([IS_ACTIVE] ASC)

    PRINT '✅ Table DBREPORTCOLUMN created successfully'
END
ELSE
BEGIN
    PRINT 'ℹ️ Table DBREPORTCOLUMN already exists'
END

-- 4. Report Group Configuration (Separate for performance)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DBREPORTGROUP]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DBREPORTGROUP] (
        [ID] INT IDENTITY(1,1) NOT NULL,
        [KODEREPORT] NVARCHAR(50) NOT NULL,
        [GROUP_FIELD] NVARCHAR(100) NOT NULL,
        [GROUP_LABEL] NVARCHAR(200) NULL,
        [SHOW_HEADER] BIT NOT NULL DEFAULT 1,
        [SHOW_FOOTER] BIT NOT NULL DEFAULT 1,
        [SHOW_SUM] BIT NOT NULL DEFAULT 0,
        [SUM_FIELDS] NTEXT NULL,
        [PAGE_BREAK] BIT NOT NULL DEFAULT 0,
        [SORT_ORDER] INT NOT NULL DEFAULT 0,
        [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
        [CREATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        [UPDATED_AT] DATETIME NOT NULL DEFAULT GETDATE(),
        CONSTRAINT [PK_DBREPORTGROUP] PRIMARY KEY CLUSTERED ([ID] ASC)
    )

    -- Create indexes
    CREATE NONCLUSTERED INDEX [IX_REPORTGROUP_CODE_ORDER] ON [dbo].[DBREPORTGROUP]
    ([KODEREPORT] ASC, [SORT_ORDER] ASC)

    CREATE NONCLUSTERED INDEX [IX_REPORTGROUP_ACTIVE] ON [dbo].[DBREPORTGROUP]
    ([IS_ACTIVE] ASC)

    PRINT '✅ Table DBREPORTGROUP created successfully'
END
ELSE
BEGIN
    PRINT 'ℹ️ Table DBREPORTGROUP already exists'
END

-- Create trigger untuk auto-update UPDATED_AT (SQL Server 2008 compatible)
-- Trigger untuk DBREPORTCONFIG
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE name = 'TR_DBREPORTCONFIG_UPDATE')
BEGIN
    EXEC('
    CREATE TRIGGER [dbo].[TR_DBREPORTCONFIG_UPDATE]
    ON [dbo].[DBREPORTCONFIG]
    AFTER UPDATE
    AS
    BEGIN
        SET NOCOUNT ON;
        UPDATE [dbo].[DBREPORTCONFIG]
        SET [UPDATED_AT] = GETDATE()
        FROM [dbo].[DBREPORTCONFIG] t
        INNER JOIN inserted i ON t.[ID] = i.[ID]
    END
    ')
    PRINT '✅ Trigger TR_DBREPORTCONFIG_UPDATE created'
END

-- Trigger untuk DBREPORTHEADER
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE name = 'TR_DBREPORTHEADER_UPDATE')
BEGIN
    EXEC('
    CREATE TRIGGER [dbo].[TR_DBREPORTHEADER_UPDATE]
    ON [dbo].[DBREPORTHEADER]
    AFTER UPDATE
    AS
    BEGIN
        SET NOCOUNT ON;
        UPDATE [dbo].[DBREPORTHEADER]
        SET [UPDATED_AT] = GETDATE()
        FROM [dbo].[DBREPORTHEADER] t
        INNER JOIN inserted i ON t.[ID] = i.[ID]
    END
    ')
    PRINT '✅ Trigger TR_DBREPORTHEADER_UPDATE created'
END

-- Trigger untuk DBREPORTCOLUMN
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE name = 'TR_DBREPORTCOLUMN_UPDATE')
BEGIN
    EXEC('
    CREATE TRIGGER [dbo].[TR_DBREPORTCOLUMN_UPDATE]
    ON [dbo].[DBREPORTCOLUMN]
    AFTER UPDATE
    AS
    BEGIN
        SET NOCOUNT ON;
        UPDATE [dbo].[DBREPORTCOLUMN]
        SET [UPDATED_AT] = GETDATE()
        FROM [dbo].[DBREPORTCOLUMN] t
        INNER JOIN inserted i ON t.[ID] = i.[ID]
    END
    ')
    PRINT '✅ Trigger TR_DBREPORTCOLUMN_UPDATE created'
END

-- Trigger untuk DBREPORTGROUP
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE name = 'TR_DBREPORTGROUP_UPDATE')
BEGIN
    EXEC('
    CREATE TRIGGER [dbo].[TR_DBREPORTGROUP_UPDATE]
    ON [dbo].[DBREPORTGROUP]
    AFTER UPDATE
    AS
    BEGIN
        SET NOCOUNT ON;
        UPDATE [dbo].[DBREPORTGROUP]
        SET [UPDATED_AT] = GETDATE()
        FROM [dbo].[DBREPORTGROUP] t
        INNER JOIN inserted i ON t.[ID] = i.[ID]
    END
    ')
    PRINT '✅ Trigger TR_DBREPORTGROUP_UPDATE created'
END

PRINT '🎉 All hybrid report system tables created successfully!'
PRINT '📊 Tables created:'
PRINT '   - DBREPORTCONFIG (hybrid configuration)'
PRINT '   - DBREPORTHEADER (header settings)'
PRINT '   - DBREPORTCOLUMN (column layout)'
PRINT '   - DBREPORTGROUP (grouping configuration)'
PRINT '✅ Ready for Phase 1 testing!'